= asciidoc-hs

Extensible and lossless parser for the lightweight markup language https://asciidoctor.org/docs/what-is-asciidoc/[AsciiDoc] that can be used as a https://pandoc.org/[Pandoc] front-end.

== Intended Features

[NOTE]
WIP. Virtually starting out.

- [ ] Full compatibility with https://asciidoctor.org[Asciidoctor] and with the result of the  https://www.eclipse.org/org/workinggroups/asciidoc-charter.php[AsciiDoc standardization process] (long-term goal).
- [ ] Generates Pandoc JSON. Other back-ends can be easily added.
- [ ] Complete and precise source mapping information can be attached to the output.
- [ ] Modular and extensible design: some syntactic features can be disabled and others can be easily added.
- [ ] Scriptable in a similar way to Pandoc, but using and AST/DOM that is specific to AsciiDoc and fully supports the result of the standardization effort (long-term goal).
- [ ] Can be used for (lossless) source-to-source transformations (long-term goal).
- [ ] Implemented in Haskell.

== Acknowledgements

This work is supported by a https://boards.greenhouse.io/tweag/jobs/4638654002[Tweag Open Source Fellowship].

== Contributions

Contributions are Welcome!
Contact me at gmarpons at mailbox.org.
