= asciidoc-hs

ifndef::env-github[]
:icons: font
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Variables:
:release-version:
// URLs:
:url-repo: https://github.com/gmarpons/asciidoc-hs

WARNING: This project is in its early stages.
Don't expect to use it in anything relevant yet.

`asciidoc-hs` is a parser for the lightweight markup language https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc] that can be used as a https://pandoc.org/[Pandoc] front-end.

It draws on https://github.com/jgm/commonmark-hs[`commonmark-hs`] and is written in pure Haskell.

ifdef::env-github[]
image:https://github.com/gmarpons/asciidoc-hs/workflows/CI/badge.svg[Build Status (GitHub Actions),link={url-repo}/actions]
endif::[]

== Planned Features

- [ ] Full compatibility with https://asciidoctor.org[Asciidoctor] and with the result of the  https://www.eclipse.org/org/workinggroups/asciidoc-charter.php[AsciiDoc standardization process] (long-term goal).
- [ ] Generates Pandoc JSON. Other back-ends can be easily added.
- [ ] Complete and precise source mapping information can be attached to the output.
- [ ] Modular and extensible design: some syntactic features can be disabled and others can be easily added.
- [ ] Scriptable in a similar way to Pandoc, but using and AST/DOM that is specific to AsciiDoc and fully supports the result of the standardization effort (long-term goal).
- [ ] Can be used for (lossless) source-to-source transformations (long-term goal).

== Install

_Comming soon_.

== Use

_Comming soon_.

== Contribute

Contributions are Welcome!
Contact me at gmarpons at mailbox.org.

== Acknowledgements

This work has been supported by a https://www.tweag.io/blog/2020-02-14-os-fellowship/[Tweag Open Source Fellowship].
